// Code generated by MockGen. DO NOT EDIT.
// Source: ./offer_core.go
//
// Generated by this command:
//
//	mockgen -source=./offer_core.go -destination=../../../test/mocks/dataaccess/db/offer_core_mock.go -package=mockdatabase
//

// Package mockdatabase is a generated GoMock package.
package mockdatabase

import (
	gomock "go.uber.org/mock/gomock"
)

// MockOfferAccessor is a mock of OfferAccessor interface.
type MockOfferAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockOfferAccessorMockRecorder
}

// MockOfferAccessorMockRecorder is the mock recorder for MockOfferAccessor.
type MockOfferAccessorMockRecorder struct {
	mock *MockOfferAccessor
}

// NewMockOfferAccessor creates a new mock instance.
func NewMockOfferAccessor(ctrl *gomock.Controller) *MockOfferAccessor {
	mock := &MockOfferAccessor{ctrl: ctrl}
	mock.recorder = &MockOfferAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfferAccessor) EXPECT() *MockOfferAccessorMockRecorder {
	return m.recorder
}
