auth:
  token:
    duration: 24h
    rs512_key_pair_bit_size: 2048
database:
  type: "mysql"
  host: "0.0.0.0"
  port: 3306
  username: "root"
  password: "secret"
  database: "epfyi_auth"
grpc:
  address: "0.0.0.0:8080"
log:
  level: "debug" # [debug, info, warn, error, panic]
cache:
  type: "redis" # [redis, in-memory]
  addr: "0.0.0.0:6379"
  username: ""
  password: ""
  db: 0