version: "3.8"

services:
    mysql:
        image: mysql:8.3.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: goload
        ports:
            - "3306:3306"
