name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  offer_service:
    name: Offer Service CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Change directory to offer_service
      run: cd ./offer_service

    - name: Install dependencies
      run: go mod tidy

    - name: Lint
      run: go run golang.org/x/lint/golint ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
